import Stripe from "stripe";

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY || "sk_test_placeholder", {
  apiVersion: "2023-10-16" as Stripe.LatestApiVersion,
  typescript: true,
});

export const PRICING_TIERS = [
  {
    name: "Free",
    tier: "free" as const,
    price: 0,
    priceId: "",
    description: "Perfect for getting started with AI content creation",
    features: [
      "5 content packages per month",
      "10 hooks per day",
      "2 scripts per day",
      "1 thumbnail concept per day",
      "10 templates",
      "Basic calendar",
      "Community support",
    ],
    limits: {
      content_packages: 5,
      hooks_per_day: 10,
      scripts_per_day: 2,
      thumbnails_per_day: 1,
      templates: 10,
      calendar_entries: 30,
    },
  },
  {
    name: "Creator",
    tier: "creator" as const,
    price: 19.99,
    priceId: process.env.STRIPE_CREATOR_PRICE_ID || "price_creator",
    description: "For serious content creators ready to scale",
    features: [
      "50 content packages per month",
      "Unlimited hooks",
      "20 scripts per day",
      "10 thumbnail concepts per day",
      "All 50+ templates",
      "AI-powered calendar",
      "Performance analytics",
      "Teleprompter mode",
      "Priority support",
      "Export all formats",
    ],
    limits: {
      content_packages: 50,
      hooks_per_day: -1,
      scripts_per_day: 20,
      thumbnails_per_day: 10,
      templates: -1,
      calendar_entries: -1,
    },
    popular: true,
  },
  {
    name: "Agency",
    tier: "agency" as const,
    price: 49.99,
    priceId: process.env.STRIPE_AGENCY_PRICE_ID || "price_agency",
    description: "For teams and agencies managing multiple creators",
    features: [
      "Unlimited content packages",
      "Unlimited hooks",
      "Unlimited scripts",
      "Unlimited thumbnail concepts",
      "All 50+ templates",
      "AI-powered calendar",
      "Advanced analytics & reports",
      "Teleprompter mode",
      "Team collaboration (5 seats)",
      "API access",
      "White-label exports",
      "Dedicated account manager",
      "Custom templates",
    ],
    limits: {
      content_packages: -1,
      hooks_per_day: -1,
      scripts_per_day: -1,
      thumbnails_per_day: -1,
      templates: -1,
      calendar_entries: -1,
    },
  },
];
